import { Queue } from "bullmq";
import { connection } from "../config/redis.js";

// Initialize the asynchronous job queue
export const aiJobQueue = new Queue("ai-analysis-queue", { connection });

// Prevent BullMQ queue connection errors from crashing the app when Redis is offline
aiJobQueue.on('error', (err) => {
  if (err.code !== 'ECONNREFUSED') console.warn('BullMQ Queue Error:', err.message);
});

// Catch errors on BullMQ's internally duplicated Redis clients
aiJobQueue.client.then(client => client.on('error', (err) => {}));

/**
 * Enqueues a new medical report for processing.
 * @param {string} jobId - A unique identifier for the job (generated by Express).
 * @param {string} rawText - The unmasked OCR text from the uploaded PDF.
 */
export async function enqueueMedicalReport(jobId, rawText) {
  // Add job to BullMQ
  await aiJobQueue.add(
    "process-report", 
    { rawPdfText: rawText }, 
    {
      jobId: jobId, // Explicit ID so the frontend can listen to the exact WebSocket room
      attempts: 3,  // Retry up to 3 times on hard infrastructure failures
      backoff: {
        type: "exponential",
        delay: 2000,
      },
    }
  );
  return jobId;
}
